### ISSUE TITLE
Country Code migration maxing out after country plugin installed

### ISSUE THREAD

**Issue by dandavies23** [dandavies23/barre-fitness#9]

**Comment by dandavies23** [comment]
**Reproduce:** `pip3 install django-countries==7.2.1` 
`python3 manage.py migrate `
**Error message:** ```
psycopg2.errors.StringDataRightTruncation: value too long for type character varying(2)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
```

**Priority / Severity:** P3 no discernable affect as yet.

**Comment by dandavies23** [comment]
Reproduce: python
